import { formatDuration } from '../util/duration';
import { pluralize } from '../util/pluralize';

export type ReportStepState = 'passed' | 'failed' | 'skipped';
export type ReportStatus = 'success' | 'failure' | 'cancelled';

export interface ReportStep {
  readonly index: number;
  readonly lineNumber: number;
  readonly display: string;
  readonly state: ReportStepState;
  readonly durationMs?: number;
  readonly stdout?: string;
  readonly stderr?: string;
  readonly errorMessage?: string;
}

export interface ReportData {
  readonly scriptName: string;
  readonly scriptPath: string;
  readonly startedAt: number;
  readonly durationMs: number;
  readonly status: ReportStatus;
  readonly steps: readonly ReportStep[];
}

export function renderReport(data: ReportData): string {
  const passed = data.steps.filter((s) => s.state === 'passed').length;
  const failed = data.steps.filter((s) => s.state === 'failed').length;
  const skipped = data.steps.filter((s) => s.state === 'skipped').length;
  const startedIso = new Date(data.startedAt).toISOString();
  const startedHuman = new Date(data.startedAt).toLocaleString();

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Agent Device — ${escapeHtml(data.scriptName)}</title>
  <style>${REPORT_CSS}</style>
</head>
<body data-status="${data.status}">
  <header class="page-header">
    <div class="title">
      <h1>${escapeHtml(data.scriptName)}</h1>
      <span class="badge ${badgeClass(data.status)}">${statusLabel(data.status)}</span>
    </div>
    <dl class="meta">
      <div><dt>Duration</dt><dd>${escapeHtml(formatDuration(data.durationMs))}</dd></div>
      <div><dt>Started</dt><dd><time datetime="${escapeHtml(startedIso)}">${escapeHtml(startedHuman)}</time></dd></div>
      <div><dt>Steps</dt><dd>${pluralize(data.steps.length, 'step')}</dd></div>
      <div><dt>Path</dt><dd><code>${escapeHtml(data.scriptPath)}</code></dd></div>
    </dl>
  </header>

  <div class="toolbar">
    <label class="search">
      <span class="search-icon" aria-hidden="true">⌕</span>
      <input id="search" type="search" placeholder="Filter steps (press / to focus)" autocomplete="off" spellcheck="false" />
      <kbd class="search-hint">/</kbd>
    </label>
    <div class="chips" role="tablist" aria-label="Filter by state">
      <button class="chip" role="tab" aria-selected="true" data-filter="all">All <span class="chip-count">${data.steps.length}</span></button>
      <button class="chip passed" role="tab" aria-selected="false" data-filter="passed">Passed <span class="chip-count">${passed}</span></button>
      <button class="chip failed" role="tab" aria-selected="false" data-filter="failed">Failed <span class="chip-count">${failed}</span></button>
      <button class="chip skipped" role="tab" aria-selected="false" data-filter="skipped">Skipped <span class="chip-count">${skipped}</span></button>
    </div>
    <div class="toolbar-actions">
      <button id="toggle-all" class="ghost" aria-pressed="false">Expand all</button>
    </div>
  </div>

  <main>
    ${data.steps.length === 0 ? '<p class="empty">No steps recorded.</p>' : renderStepList(data.steps)}
    <p id="no-results" class="empty" hidden>No steps match the current filter.</p>
  </main>

  <footer>
    <span>Generated by Agent Device DevTools for VS Code · <a href="https://github.com/azizbecha/agent-device-vscode" target="_blank" rel="noopener">source</a></span>
  </footer>

  <script>${REPORT_JS}</script>
</body>
</html>`;
}

function renderStepList(steps: readonly ReportStep[]): string {
  return `<ol class="steps">${steps.map(renderStep).join('')}</ol>`;
}

function renderStep(step: ReportStep): string {
  const dur = step.durationMs != null ? formatDuration(step.durationMs) : '';
  const body = renderStepBody(step);
  const haystack = `${step.lineNumber} ${step.display} ${step.errorMessage ?? ''}`.toLowerCase();
  return `<li class="step ${step.state}" data-state="${step.state}" data-search="${escapeHtml(haystack)}">
    <div class="step-header">
      <span class="step-icon" aria-label="${step.state}">${stepGlyph(step.state)}</span>
      <span class="step-line">L${step.lineNumber}</span>
      <span class="step-text"><code>${escapeHtml(step.display)}</code></span>
      <span class="step-duration">${escapeHtml(dur)}</span>
      <button class="copy-btn ghost" type="button" data-copy="${escapeHtml(step.display)}" title="Copy command">⧉</button>
    </div>
    ${body}
  </li>`;
}

function renderStepBody(step: ReportStep): string {
  const blocks: string[] = [];
  if (step.errorMessage) {
    blocks.push(detailsBlock('Error', step.errorMessage, true, 'error'));
  }
  if (step.stderr?.trim()) {
    blocks.push(detailsBlock('stderr', step.stderr.trim(), false));
  }
  if (step.stdout?.trim()) {
    blocks.push(detailsBlock('stdout', step.stdout.trim(), false));
  }
  if (blocks.length === 0) {
    return '';
  }
  return `<div class="step-body">${blocks.join('')}</div>`;
}

function detailsBlock(
  label: string,
  text: string,
  openByDefault: boolean,
  extraClass = '',
): string {
  return `<details class="${extraClass}"${openByDefault ? ' open' : ''}>
    <summary>
      <span>${escapeHtml(label)}</span>
      <button class="copy-btn ghost" type="button" data-copy-target>⧉ Copy</button>
    </summary>
    <pre>${escapeHtml(text)}</pre>
  </details>`;
}

function statusLabel(status: ReportStatus): string {
  switch (status) {
    case 'success':
      return 'Pass';
    case 'failure':
      return 'Fail';
    case 'cancelled':
      return 'Cancelled';
  }
}

function badgeClass(status: ReportStatus): string {
  switch (status) {
    case 'success':
      return 'pass';
    case 'failure':
      return 'fail';
    case 'cancelled':
      return 'cancelled';
  }
}

function stepGlyph(state: ReportStepState): string {
  switch (state) {
    case 'passed':
      return '✓';
    case 'failed':
      return '✗';
    case 'skipped':
      return '−';
  }
}

const HTML_ENTITIES: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (ch) => HTML_ENTITIES[ch] ?? ch);
}

const REPORT_CSS = `
:root {
  --fg: #1f2328;
  --fg-muted: #59636e;
  --fg-subtle: #848d97;
  --bg: #ffffff;
  --bg-soft: #f6f8fa;
  --border: rgba(31, 35, 40, 0.15);
  --border-strong: rgba(31, 35, 40, 0.3);
  --pass: #1a7f37;
  --fail: #d1242f;
  --warn: #9a6700;
  --link: #0969da;
  --code-bg: rgba(175, 184, 193, 0.18);
  --hover: rgba(208, 215, 222, 0.32);
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
    --fg: #e6edf3;
    --fg-muted: #9198a1;
    --fg-subtle: #656d76;
    --bg: #0d1117;
    --bg-soft: #161b22;
    --border: rgba(240, 246, 252, 0.1);
    --border-strong: rgba(240, 246, 252, 0.2);
    --pass: #3fb950;
    --fail: #f85149;
    --warn: #d29922;
    --link: #58a6ff;
    --code-bg: rgba(110, 118, 129, 0.4);
    --hover: rgba(177, 186, 196, 0.12);
  }
}

* { box-sizing: border-box; }

html, body {
  margin: 0;
  padding: 0;
  background: var(--bg);
  color: var(--fg);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  font-size: 14px;
  line-height: 1.5;
}

body {
  max-width: 1080px;
  margin: 0 auto;
  padding: 24px 24px 64px;
}

.page-header {
  border-bottom: 1px solid var(--border);
  padding-bottom: 16px;
  margin-bottom: 16px;
}

.title { display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }
.title h1 { font-size: 20px; margin: 0; font-weight: 600; letter-spacing: -0.01em; }

.badge {
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: white;
}
.badge.pass      { background: var(--pass); }
.badge.fail      { background: var(--fail); }
.badge.cancelled { background: var(--fg-muted); }

dl.meta {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 12px 24px;
  margin: 16px 0 0;
}
dl.meta > div { display: flex; flex-direction: column; gap: 2px; }
dl.meta dt { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--fg-muted); margin: 0; }
dl.meta dd { margin: 0; font-variant-numeric: tabular-nums; word-break: break-all; }
dl.meta code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  background: var(--code-bg);
  padding: 1px 6px;
  border-radius: 4px;
  font-size: 12px;
}

.toolbar {
  position: sticky;
  top: 0;
  z-index: 5;
  background: var(--bg);
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 0;
  border-bottom: 1px solid var(--border);
  flex-wrap: wrap;
}

.search {
  position: relative;
  display: flex;
  align-items: center;
  flex: 1 1 280px;
  min-width: 200px;
}
.search-icon {
  position: absolute;
  left: 10px;
  color: var(--fg-subtle);
  font-size: 14px;
  pointer-events: none;
}
.search input {
  width: 100%;
  padding: 6px 32px 6px 32px;
  font: inherit;
  background: var(--bg-soft);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 6px;
  outline: none;
  transition: border-color 0.1s, box-shadow 0.1s;
}
.search input:focus { border-color: var(--link); box-shadow: 0 0 0 3px color-mix(in srgb, var(--link) 25%, transparent); }
.search-hint {
  position: absolute;
  right: 10px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 11px;
  color: var(--fg-subtle);
  background: var(--code-bg);
  padding: 1px 6px;
  border-radius: 4px;
  pointer-events: none;
}

.chips { display: flex; gap: 4px; flex-wrap: wrap; }
.chip {
  font: inherit;
  font-size: 12px;
  padding: 4px 10px;
  background: var(--bg-soft);
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 999px;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  gap: 6px;
}
.chip:hover { background: var(--hover); }
.chip[aria-selected="true"] { border-color: var(--border-strong); background: var(--code-bg); }
.chip.passed[aria-selected="true"] { color: var(--pass); border-color: color-mix(in srgb, var(--pass) 50%, transparent); }
.chip.failed[aria-selected="true"] { color: var(--fail); border-color: color-mix(in srgb, var(--fail) 50%, transparent); }
.chip.skipped[aria-selected="true"] { color: var(--fg-muted); border-color: var(--border-strong); }
.chip-count {
  font-variant-numeric: tabular-nums;
  font-size: 11px;
  color: var(--fg-muted);
  background: var(--bg);
  border-radius: 999px;
  padding: 0 6px;
  min-width: 20px;
  text-align: center;
}
.chip[aria-selected="true"] .chip-count { color: inherit; }

.toolbar-actions { display: flex; gap: 8px; margin-left: auto; }

button.ghost {
  font: inherit;
  font-size: 12px;
  padding: 4px 10px;
  background: transparent;
  color: var(--fg);
  border: 1px solid var(--border);
  border-radius: 6px;
  cursor: pointer;
}
button.ghost:hover { background: var(--hover); }

ol.steps {
  list-style: none;
  margin: 16px 0 0;
  padding: 0;
  border: 1px solid var(--border);
  border-radius: 8px;
  overflow: hidden;
}

li.step + li.step { border-top: 1px solid var(--border); }
li.step.passed   { background: var(--bg); }
li.step.failed   { background: color-mix(in srgb, var(--fail) 8%, var(--bg)); }
li.step.skipped  { background: var(--bg-soft); color: var(--fg-muted); }
li.step[hidden]  { display: none; }

.step-header {
  display: grid;
  grid-template-columns: 22px 44px 1fr auto 32px;
  align-items: center;
  gap: 12px;
  padding: 10px 14px;
}

.step-icon {
  font-size: 14px;
  font-weight: 700;
  text-align: center;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}
li.step.passed  .step-icon { color: var(--pass); }
li.step.failed  .step-icon { color: var(--fail); }
li.step.skipped .step-icon { color: var(--fg-muted); }

.step-line {
  font-size: 11px;
  color: var(--fg-muted);
  font-variant-numeric: tabular-nums;
  text-align: right;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.step-text { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.step-text code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 13px; }

.step-duration {
  font-size: 12px;
  color: var(--fg-muted);
  font-variant-numeric: tabular-nums;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
}

.step-header .copy-btn {
  font-size: 14px;
  padding: 2px 6px;
  border-radius: 4px;
  border: 1px solid transparent;
  color: var(--fg-muted);
  background: transparent;
  cursor: pointer;
  opacity: 0;
  transition: opacity 0.1s;
}
li.step:hover .step-header .copy-btn { opacity: 1; }
.step-header .copy-btn:hover { color: var(--fg); background: var(--hover); }
.step-header .copy-btn.copied { color: var(--pass); opacity: 1; }

.step-body {
  padding: 0 14px 12px 78px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

details {
  border: 1px solid var(--border);
  border-radius: 6px;
  background: var(--bg-soft);
  padding: 6px 10px;
}
details.error { border-color: color-mix(in srgb, var(--fail) 40%, var(--border)); }
details summary {
  cursor: pointer;
  font-size: 12px;
  color: var(--fg-muted);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  display: flex;
  align-items: center;
  justify-content: space-between;
  list-style: none;
}
details summary::-webkit-details-marker { display: none; }
details summary::before {
  content: "▸";
  display: inline-block;
  margin-right: 6px;
  transition: transform 0.1s;
}
details[open] summary::before { transform: rotate(90deg); }
details summary > .copy-btn {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 4px;
  border: 1px solid transparent;
  color: var(--fg-muted);
  background: transparent;
  cursor: pointer;
  text-transform: none;
  letter-spacing: 0;
  font-weight: 500;
}
details summary > .copy-btn:hover { background: var(--hover); color: var(--fg); }
details summary > .copy-btn.copied { color: var(--pass); }

pre {
  margin: 8px 0 0;
  padding: 10px 12px;
  background: var(--code-bg);
  border-radius: 4px;
  overflow: auto;
  max-height: 280px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px;
  line-height: 1.45;
  white-space: pre-wrap;
  word-break: break-word;
}

.empty {
  text-align: center;
  color: var(--fg-muted);
  padding: 24px;
}

footer {
  margin-top: 32px;
  font-size: 11px;
  color: var(--fg-muted);
  text-align: center;
}
footer a { color: var(--link); text-decoration: none; }
footer a:hover { text-decoration: underline; }

@media (max-width: 640px) {
  body { padding: 16px 14px 48px; }
  .toolbar-actions { margin-left: 0; }
  .step-body { padding-left: 14px; }
  .step-header { grid-template-columns: 22px 44px 1fr auto; }
  .step-header .copy-btn { display: none; }
}
`;

const REPORT_JS = `
(function () {
  const search = document.getElementById('search');
  const chips = Array.from(document.querySelectorAll('.chip[data-filter]'));
  const toggleAll = document.getElementById('toggle-all');
  const noResults = document.getElementById('no-results');
  const steps = Array.from(document.querySelectorAll('li.step'));
  let activeFilter = 'all';

  function applyFilters() {
    const query = (search.value || '').trim().toLowerCase();
    let visible = 0;
    for (const step of steps) {
      const stateMatch = activeFilter === 'all' || step.dataset.state === activeFilter;
      const haystack = step.dataset.search || '';
      const textMatch = !query || haystack.indexOf(query) !== -1;
      const show = stateMatch && textMatch;
      step.hidden = !show;
      if (show) visible++;
    }
    if (noResults) noResults.hidden = visible > 0;
  }

  search.addEventListener('input', applyFilters);
  search.addEventListener('keydown', function (e) { if (e.key === 'Escape') { search.value = ''; applyFilters(); } });

  chips.forEach(function (chip) {
    chip.addEventListener('click', function () {
      activeFilter = chip.dataset.filter || 'all';
      chips.forEach(function (c) { c.setAttribute('aria-selected', String(c === chip)); });
      applyFilters();
    });
  });

  if (toggleAll) {
    toggleAll.addEventListener('click', function () {
      const allDetails = document.querySelectorAll('details');
      const expand = toggleAll.getAttribute('aria-pressed') !== 'true';
      allDetails.forEach(function (d) { d.open = expand; });
      toggleAll.setAttribute('aria-pressed', String(expand));
      toggleAll.textContent = expand ? 'Collapse all' : 'Expand all';
    });
  }

  document.addEventListener('keydown', function (e) {
    if (e.key === '/' && document.activeElement !== search && !e.metaKey && !e.ctrlKey) {
      e.preventDefault();
      search.focus();
      search.select();
    }
  });

  document.addEventListener('click', function (e) {
    const target = e.target;
    if (!(target instanceof HTMLElement)) return;
    const btn = target.closest('.copy-btn');
    if (!btn) return;
    e.preventDefault();
    e.stopPropagation();
    let text = '';
    if (btn.dataset.copy != null) {
      text = btn.dataset.copy;
    } else if (btn.hasAttribute('data-copy-target')) {
      const details = btn.closest('details');
      const pre = details && details.querySelector('pre');
      if (pre) text = pre.textContent || '';
    }
    if (!text) return;
    Promise.resolve(navigator.clipboard.writeText(text))
      .then(function () { flashCopied(btn); })
      .catch(function () { flashCopied(btn, 'failed'); });
  });

  function flashCopied(btn, mode) {
    const original = btn.textContent;
    btn.classList.add('copied');
    btn.textContent = mode === 'failed' ? '✗ failed' : '✓ copied';
    setTimeout(function () {
      btn.classList.remove('copied');
      btn.textContent = original;
    }, 1200);
  }
})();
`;
